# Generated by Django 5.0.1 on 2024-07-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0002_alter_recipe_main_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="upload_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="main_image",
            field=models.ImageField(blank=True, upload_to="recipe/"),
        ),
    ]
