# Generated by Django 5.0.1 on 2024-07-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0003_recipe_upload_date_alter_recipe_main_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
