# Generated by Django 5.0.1 on 2024-07-04 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0004_alter_recipe_options_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="piece_weight",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recipeingridient",
            name="weight_unit",
            field=models.CharField(
                choices=[
                    ("ML", "ml"),
                    ("L", "l"),
                    ("G", "g"),
                    ("KG", "kg"),
                    ("PIECES", "Pieces"),
                ],
                default="G",
                max_length=23,
            ),
        ),
    ]
