# Generated by Django 5.0.6 on 2024-07-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0005_product_piece_weight_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingridient",
            name="weight_unit",
            field=models.CharField(
                choices=[
                    ("ML", "ml"),
                    ("L", "l"),
                    ("G", "g"),
                    ("KG", "kg"),
                    ("PIECES", "pcs"),
                ],
                default="G",
                max_length=23,
            ),
        ),
    ]
