# Generated by Django 5.0.6 on 2024-07-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0006_alter_recipeingridient_weight_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="is_dividible",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Diet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calloires_per_dish", models.IntegerField(default=0)),
                ("forriben_categories", models.ManyToManyField(to="recipe.category")),
            ],
        ),
    ]
