# Generated by Django 5.0.6 on 2024-07-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0007_recipe_is_dividible_diet"),
    ]

    operations = [
        migrations.AddField(
            model_name="diet",
            name="name",
            field=models.CharField(blank=True, max_length=23),
        ),
    ]
