# Generated by Django 5.0.6 on 2024-07-06 06:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0009_alter_diet_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diet",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="recipeingridient",
            options={"ordering": ["-id"]},
        ),
        migrations.RenameField(
            model_name="diet",
            old_name="calloires_per_dish",
            new_name="caloires_per_dish",
        ),
    ]
