# Generated by Django 5.0.6 on 2024-07-15 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0010_alter_diet_options_alter_recipeingridient_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingridient",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recipe_ingridients",
                to="recipe.product",
            ),
        ),
    ]
