# Generated by Django 5.0.6 on 2024-08-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0013_alter_recipeingridient_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngridientGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63, unique=True)),
                (
                    "ingridients",
                    models.ManyToManyField(blank=True, to="recipe.recipeingridient"),
                ),
            ],
        ),
    ]
