# Generated by Django 5.0.6 on 2024-08-01 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0014_ingridientgroup"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IngridientGroup",
        ),
    ]
