# Generated by Django 5.0.6 on 2024-08-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0015_delete_ingridientgroup"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="recipe",
            name="recipe_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
