# Generated by Django 5.0.6 on 2024-07-05 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0007_recipe_is_dividible_diet"),
        ("user_system", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diet", models.ManyToManyField(blank=True, to="recipe.diet")),
                (
                    "fav_categories",
                    models.ManyToManyField(
                        blank=True, related_name="fav_categories", to="recipe.category"
                    ),
                ),
                (
                    "fav_products",
                    models.ManyToManyField(
                        blank=True, related_name="fav_products", to="recipe.product"
                    ),
                ),
                (
                    "hate_categories",
                    models.ManyToManyField(
                        blank=True, related_name="hate_categories", to="recipe.category"
                    ),
                ),
                (
                    "hates_products",
                    models.ManyToManyField(
                        blank=True, related_name="hate_products", to="recipe.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
