# Generated by Django 5.0.6 on 2024-07-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_system", "0002_userpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
