# Generated by Django 5.0.6 on 2024-07-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0012_recipe_likes"),
        ("user_system", "0005_alter_userpreference_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="favorite",
            field=models.ManyToManyField(
                blank=True, related_name="users_favorite", to="recipe.recipe"
            ),
        ),
    ]
