# Generated by Django 5.0.6 on 2024-08-01 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_system", "0006_customuser_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preference",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
